### ISSUE TITLE
change some variables to enums

### ISSUE THREAD

**Issue by ConfettiRaindrop** [FRC-1294/scouting-app#61]
Currently MatchData is using enums to store data (if you want to learn more about emuns and what they are/how to initialize them look [here](https://www.w3schools.com/java/java_enums.asp). On your pages are variables that need to be changed to match MatchData, these include

Auto:
- Robot contact

Teleop:
- robot note aquisition

Endgame:
- chain result
- harmony result
- trap result

Originally I had these set in MatchData which is why I have some example code here for you guys to use, but it was mentioned to me that it's better to have these conversions at the beginning of the data journey, not at the end and for the people that collect the data to make these so that if you guys decide to change something related to these variables you'll have a better time of remembering to also switch the data translation. I've made all of the enums public so you can reach them from your pages.

Example for Note aquisition:
```        if (floor && source){
            this.noteAcquired =  NoteAcquisition.Both;
        } else if (floor && !source) {
            this.noteAcquired =  NoteAcquisition.Floor;
        } else if (!floor && source) {
            this.noteAcquired =  NoteAcquisition.Source;
        } else {
            this.noteAcquired = NoteAcquisition.None;
        }```

Example for chaining:
````         switch (index){
            case 0:
                this.chaining = Chain.Nope;
                break;
            case 1:
                this.chaining = Chain.Attempted;
                break;
            case 2:
                this.chaining = Chain.Succeeded;
                break;
        }```

**Comment by MthreeJohnnyK** [comment]
im done
